insert into question(no,title,contents,section) values(question_seq.nextval, '다른은행계좌로 자동이체가 가능한가요?','네 고객님 저희 KangBank에서는 자동이체 서비스를 진행하고 있습니다.<br>상단메뉴바에 계좌이체 코너를 이용해주시면 감사하겠습니다.<br>','계좌이체')
insert into question(no,title,contents,section) values(question_seq.nextval, 'KANGBANK 인터넷뱅킹 미가입 고객입니다. 어떻게 해야하나요?','네 고객님 저희 KangBank 왼쪽 메뉴바에서 회원가입을 하시면 사용가능합니다.<br>계좌이체시에는 보안카드가 꼭 필요하므로 보안카드를 발급받아 주시기 바랍니다.<br>','계좌이체')
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드는 어떻게 발급받나요?','네 고객님 저희 KangBank에서는 보안카드를 인터넷으로 발급 받으실 수 있습니다.<br>상단메뉴바에 보안센터 코너를 이용해주시면 감사하겠습니다.<br>보안카드 발급시 이메일로 인증번호가 전송되고 인증이 성공하면 보안카드가 메일로 발송됩니다','보안카드')
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 해지가 가능한가요?','네 고객님 저희 KangBank에서는 인터넷으로 보안카드를 해지하실 수 있습니다.<br>상단메뉴바에 보안센터 코너를 이용해주시면 감사하겠습니다.<br>','보안카드')
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 재발급이 가능한가요?','네 고객님 저희 KangBank에서는 인터넷으로 보안카드를 재발급 받으실 수 있습니다.<br>상단메뉴바에 보안센터 코너를 이용해주시면 감사하겠습니다.<br>재발급은 보안카드 발급절차와 동일합니다.','보안카드')
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 발급을 신청했습니다. 어디서 볼 수 있나요?','네 고객님 저희 KangBank에서는 고객님의 이메일로 보안카드를 보내드리고 있습니다.<br>이메일에서 확인해 주시면 감사하겠습니다.<br>','보안카드')
insert into question(no,title,contents,section) values(question_seq.nextval, 'KANGBANK에 적금을 하려고 합니다. 이율이 얼마나 되나요?','네 고객님 저희 KangBank에서는 다양한 이율이 적용되고 있는 적금 서비스를 제공하고 있습니다.<br>상단메뉴바에 상품정보 코너를 이용해주시면 감사하겠습니다.<br>','적금')
insert into question(no,title,contents,section) values(question_seq.nextval, 'KANGBANK에서 대출을 하려고 합니다. 대출이자가 얼마나 되나요?','네 고객님 저희 KangBank에서는 다양한 이자율이 적용되고 있는 대출 서비스를 제공하고 있습니다.<br>상단메뉴바에 상품정보 코너를 이용해주시면 감사하겠습니다.<br>','대출')
insert into question(no,title,contents,section) values(question_seq.nextval, '이체시에 보안카드가 필요한가요?','네 고객님 저희 KangBank에서는 이체 시 보안유지를 위하여 보안카드 확인을 하고 있습니다.<br>보안카드가 없으면 온라인 이체가 가능하지 않으니 이점 양해바랍니다.<br>','계좌이체');
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 분실시 어떻게하면 되나요?','네 고객님 저희 KangBank에서는 보안카드 분실시 재발급을 받도록 하고 있습니다.<br>보안카드가 없으면 온라인 서비스가 가능하지 않으니 이점 양해바랍니다.<br>','보안카드');
insert into question(no,title,contents,section) values(question_seq.nextval, '다른은행계좌로 계좌이체시 수수료가 얼마인가요?','네 고객님 저희 KangBank에서는 은행마다 수수료를 다르게 책정하고 있습니다.<br>KangBank은행 내에서의 이체는 현재 수수료가 적용되지 않고 있습니다.<br>이체시에 고객님의 확인 부탁드립니다.<br>','계좌이체');
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 입력 5회 오류가 났습니다. 어떻게 해야하나요?','네 고객님 저희 KangBank에서는 보안을 위해 보안카드를 확인하고 있습니다.<br>5회 오류시에는 번거로우시더라도 은행을 방문해주시길 바랍니다.<br>양해부탁드립니다.<br>','계좌이체');
insert into question(no,title,contents,section) values(question_seq.nextval, '보안카드 입력 5회 오류가 났습니다. 어떻게 해야하나요?','네 고객님 저희 KangBank에서는 보안을 위해 보안카드를 확인하고 있습니다.<br>5회 오류시에는 번거로우시더라도 은행을 방문해주시길 바랍니다.<br>양해부탁드립니다.<br>','보안카드');
